config/routes.rb
Rockpaperscissors::Application.routes.draw do

    root to: 'rockpaperscissors#index'

    resources :rockpaperscissors

end

app/models/rockpaperscissor.rb
class Rockpaperscissor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rockpaperscissors_controller.rb
class RockpaperscissorsController < ApplicationController

	def index
		@rockpaperscissors = Rockpaperscissor.all
	end

	def show
		player_choice = Rockpaperscissor.find(params[:id]) 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rockpaperscissors_helper.rb
module RockpaperscissorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rockpaperscissors</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rockpaperscissors/index.html.erb
<h1> Welcome to Rock Paper Scissors</h1>
<% @rockpaperscissors.each do |rockpaperscissor| %>
	<% rockpaperscissor.name %>
	<% rockpaperscissor.win %>
	<% rockpaperscissor.lose %>
	<% rockpaperscissor.tie %>
	<%= link_to "Rock", rockpaperscissor_path(1) %>
	<%= link_to "Paper", rockpaperscissor_path(2) %>
	<%= link_to "Scissors", rockpaperscissor_path(3) %>
<% end %>

app/views/rockpaperscissors/show.html.erb
show.html.erb